# Utiliser une image Python légère
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY requirements.txt . 

# Installer les dépendances
RUN pip install -r requirements.txt

# Copier tout le contenu du projet
COPY . .


# Se déplacer dans le dossier "app" et lancer Streamlit
CMD ["sh", "-c", "cd app && streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0"]

